### ISSUE TITLE
Use credentials::git_credential_ask() to summon the token for a given host

### ISSUE THREAD

**Issue by jennybc** [r-lib/gh#120]
This is basically the gh analogue of what gert does for https remotes.

Basic sketch:

If the host is GitHub.com and GITHUB_PAT is set, use it.

Otherwise ask credentials to lookup / request (and then store) the PAT for GitHub.com or whatever GHE instance is implied by the `host`.

**Comment by gaborcsardi** [comment]
I think we could keep some of (?) the current flexible lookup. I.e. this: https://github.com/r-lib/gh/blob/b36672688cbf2036d3c3848118d6edd7913ef644/R/gh_token.R#L17
(If we don't keep it, that's a breaking change, although very few people use this, I am sure.)

So I think the lookup would maybe go like this:
* `GITHUB_PAT_API_GITHUB_COM` env var
* Host specific pass / token from git, if git is installed (unless opted out)
* Host specific token from keyring (if opted in)
* `GITHUB_PAT` env var.
* Generic pass / token from git, if git is installed (unless opted out)
* Generic `GITHUB_PAT` token from keyring (if opted in)

One concern I have about credentials is that `git_credential_ask()` takes anywhere between 1.5 and 3 seconds to complete. It would be great to speed this up, because otherwise we need to cache the credentials. On macOS it is about 0.1s, which is maybe OK.

Fwiw, getting the same credentials directly from the keyring is 0.0001s, so the bottleneck is in credentials or git itself. 

@jeroen do you think this can be faster on Windows?

**Comment by gaborcsardi** [comment]
It seems that the Windows version of the credential helper is just slow. It seems to contacts GitHub for some reason. So we could just use the `GITHUB_PAT` env var as a cache.

The only difficulty is that we need to be careful which env var we set, because we don't want to overwrite `GITHUB_PAT` for a GHE auth. But credentials tells us the host name, and we can use that to set an env var.

Also, we would probably only set the env var if it is not set already. It might make sense to include some of this logic in credentials itself.

**Comment by gaborcsardi** [comment]
I think this is now mostly solved via gitcreds. Will need to make sure that it is tested.

**Comment by jeroen** [comment]
Sorry for dropping the ball, thanks for getting this done!
