### ISSUE TITLE
Can gh use preview API features for the REST API that require media type specification?

### ISSUE THREAD

**Issue by ddsjoberg** [r-lib/gh#155]
Hello! Thank you for this fantastic resource!

I am trying to write a script to add a topic hashtag to some repositories.  Details here: https://docs.github.com/en/rest/reference/repos#replace-all-repository-topics
![image](https://user-images.githubusercontent.com/26774684/124198705-35129e80-da9f-11eb-98ff-2af42b1029c5.png)

There is a preview notice indicating that we MUST specify a media type in the Accept header.
![image](https://user-images.githubusercontent.com/26774684/124198803-71de9580-da9f-11eb-8044-4f2fbfc93c1f.png)

I am not sure how to pass this accept header with `gh::gh()`. Do you know if it is possible?

Thank you!

**Comment by jennybc** [comment]
In the docs for `gh::gh()`, you'll see documentation for the `.accept` argument:

`.accept` The value of the Accept HTTP header. Defaults to "application/vnd.github.v3+json" . If Accept is given in .send_headers, then that will be used. This parameter can be used to provide a custom media type, in order to access a preview feature of the API.

The examples for `gh::gh()` show use of `.accept`, although they produce such an overwhelming amount of output, that it's hard to find.

I'd visit the page, then search within it for "accept".

https://gh.r-lib.org/reference/gh.html

**Comment by ddsjoberg** [comment]
Thank you so much @jennybc for your response! Apologies for missing this in the documentation.

I hope you had a great 🇨🇦day and enjoy your  🇺🇲 independence day!
