### ISSUE TITLE
Error: GitHub PAT must have one of these forms

### ISSUE THREAD

**Issue by ocelhay** [r-lib/gh#159]
Running on my macOS Intel, R 4.1.0 and gh 1.3.0:

```
> library(gh)
> gh("/users/hadley/repos")
Error: GitHub PAT must have one of these forms:
  * 40 hexadecimal digits (older PATs)
  * A 'ghp_' prefix followed by 36 to 251 more characters (newer PATs)
Type .Last.error.trace to see where the error occurred
```

**Comment by ocelhay** [comment]
For context, that motivates my use of `gh`: https://stackoverflow.com/questions/69212782/is-it-possible-to-find-the-latest-github-release-of-a-repo-with-r/

**Comment by jennybc** [comment]
This error means what it says.

Your PAT appears to be invalid.

Sometimes this happens when people have mistakenly entered their password when prompted for a PAT.

Or perhaps you have a old-style PAT and GitHub is starting to enforce the new format introduced earlier this year.

https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/

**Comment by ocelhay** [comment]
from the doc: "You need to know the API to be able to use this client." which isn't my case.
