### ISSUE TITLE
Debug mode? Refactor gh_url()? 

### ISSUE THREAD

**Issue by jennybc** [r-lib/gh#35]
I am willing to take a crack at this but would like your approval and some vague direction.

I'm hitting a lot of new endpoints and discovering new edge cases that break `gh`.

It would be very helpful if it were easier to see the endpoint `gh()` arrives at after the `parse_endpoint()` call and to see what's left for the query or body. And then to see what the body looks like after being sent through `jsonlite::toJSON()`.

Are you generally on board with this?

If so, feel free to say anything --even very vague -- about how you would approach it and I'll try to comply.

**Comment by jennybc** [comment]
I also think refactoring that exposed the fully-substituted endpoint and the query / body, prior to making the API call, would be helpful for writing tests.

**Comment by gaborcsardi** [comment]
YES! This would be indeed great to have. 

I am not sure about the best way, so it will be somewhat experimental, but that's ok, you need to start somewhere. :)

Some random ideas:
* logging, i.e. like a verbose mode in a command line app
* callback function(s), that are called as the request is made, the response is received, etc. They can default to log to the screen, but then you can set them to `browser` or whatever you want.
* configuration via `options()`, maybe.

Since this is experimental, I don't think it needs to be fully fleshed out before we start playing with it. Something dirty is perfectly fine, just to see if it is the right direction.

**Comment by gaborcsardi** [comment]
I think we close this now.
